"""Build LogMasque.py: the whole logmasque package in one double-clickable file.

Some workstations allow Python but block .cmd and .bat files, and unpacking a
folder structure from a ZIP is one more thing to get wrong. LogMasque.py carries
every module and the web interface as plain, readable text and imports them from
memory, so nothing is unpacked or written to disk at start.

The package stays the source of truth; the file is a build artifact and is not
kept in the repository:

    python scripts/build_single_file.py                  # writes dist/LogMasque.py
    python scripts/build_single_file.py --output <file>
"""

from __future__ import annotations

import argparse
import ast
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
PACKAGE = REPO / "logmasque"
OUTPUT = REPO / "dist" / "LogMasque.py"

# __main__.py exits the interpreter on import; the bundle has its own entry point.
SKIPPED_MODULES = {"__main__.py"}

HEADER = '''#!/usr/bin/env python3
"""LogMasque in a single file. Double-click to open the interface.

Same program as the logmasque package, carried here as one file for machines on
which only Python may run. Every module and the web interface are included
below as plain text and imported from memory; nothing is unpacked or written
next to this file. The command line works as usual, for example:

    py LogMasque.py --help
    py LogMasque.py scan <folder>

Generated by scripts/build_single_file.py. Do not edit by hand: change
the package and regenerate, otherwise the next build overwrites the change.
"""

import importlib.abc
import importlib.util
import linecache
import os
import sys

'''

LOADER = '''

class _BundleImporter(importlib.abc.MetaPathFinder, importlib.abc.Loader):
    """Serves the logmasque modules carried in this file.

    It sits first on sys.meta_path, so a logmasque folder lying next to this
    file is never picked up instead. The package path stays empty, which keeps
    submodule lookups inside this file as well.
    """

    def __init__(self, bundle_path):
        self.bundle_path = bundle_path

    def _filename(self, name):
        # A path inside this file: tracebacks name the bundle, and it can never
        # collide with a real file on disk.
        parts = name.split(".") + (["__init__"] if name == "logmasque" else [])
        return os.path.join(self.bundle_path, *parts) + ".py"

    def find_spec(self, name, path=None, target=None):
        if name not in _SOURCES:
            return None
        return importlib.util.spec_from_loader(name, self, is_package=name == "logmasque")

    def create_module(self, spec):
        return None

    def get_source(self, name):
        return _SOURCES[name]

    def exec_module(self, module):
        name = module.__spec__.name
        filename = self._filename(name)
        source = _SOURCES[name]
        module.__file__ = filename
        # Lets tracebacks in the log show the failing line, as with the package.
        linecache.cache[filename] = (len(source), None, source.splitlines(True), filename)
        exec(compile(source, filename, "exec"), module.__dict__)
        if name == "logmasque.server":
            module.EMBEDDED_WEB.update(_WEB)


def _main():
    if sys.version_info < (3, 9):
        print("LogMasque needs Python 3.9 or newer, found " + sys.version.split()[0])
        return 1
    sys.meta_path.insert(0, _BundleImporter(os.path.abspath(__file__)))
    from logmasque.cli import main

    return main()


if __name__ == "__main__":
    try:
        code = _main()
    except SystemExit:
        raise
    except BaseException:
        import traceback

        traceback.print_exc()
        code = 1
    # Started by double-click, the window would close before the message can be
    # read. Ctrl+C (130) is a deliberate stop and needs no pause.
    if code not in (0, None, 130) and sys.stdin is not None and sys.stdin.isatty():
        try:
            input("\\nPress Enter to close this window.")
        except EOFError:
            pass
    sys.exit(code)
'''


def literal(text: str) -> str:
    """Return a Python literal that reproduces text exactly, readable where possible."""
    if "\x00" not in text and "\r" not in text:
        for quote in ("'''", '"""'):
            if quote not in text and not text.endswith(("\\", quote[0])):
                candidate = f"r{quote}{text}{quote}"
                if ast.literal_eval(candidate) == text:
                    return candidate
    return repr(text)


def module_name(path: Path) -> str:
    return "logmasque" if path.name == "__init__.py" else f"logmasque.{path.stem}"


def render() -> str:
    modules = sorted(p for p in PACKAGE.glob("*.py") if p.name not in SKIPPED_MODULES)
    web = sorted(p for p in (PACKAGE / "web").iterdir() if p.is_file())

    lines = [HEADER, "_SOURCES = {\n"]
    for path in modules:
        lines.append(f"    {module_name(path)!r}: {literal(path.read_text(encoding='utf-8'))},\n")
    lines.append("}\n\n_WEB = {\n")
    for path in web:
        lines.append(f"    {path.name!r}: {literal(path.read_text(encoding='utf-8'))},\n")
    lines.append("}\n")
    lines.append(LOADER)
    output = "".join(lines)

    # The bundle must carry every file byte for byte, or it is not the same program.
    tree = ast.parse(output)
    tables = {
        node.targets[0].id: ast.literal_eval(node.value)
        for node in tree.body
        if isinstance(node, ast.Assign) and getattr(node.targets[0], "id", "") in ("_SOURCES", "_WEB")
    }
    for path in modules:
        assert tables["_SOURCES"][module_name(path)] == path.read_text(encoding="utf-8"), path
    for path in web:
        assert tables["_WEB"][path.name] == path.read_text(encoding="utf-8"), path
    return output


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description="Build the single-file LogMasque.py.")
    parser.add_argument("--output", type=Path, default=OUTPUT, help=f"target file (default: {OUTPUT.relative_to(REPO)})")
    target = parser.parse_args(argv).output.resolve()
    output = render()
    target.parent.mkdir(parents=True, exist_ok=True)
    with open(target, "w", encoding="utf-8", newline="\n") as handle:  # Path.write_text has no newline before 3.10
        handle.write(output)
    print(f"{target}: {len(output.encode('utf-8')) // 1024} KB")
    return 0


if __name__ == "__main__":
    sys.exit(main())
